### ISSUE TITLE
Map page is in sitemap.kml

### ISSUE THREAD

**Issue by iainhallam** [mprins/dokuwiki-plugin-spatialhelper#17]
I've just added the spatial plugins to a site, and I can begin to see how it works (though I've submitted a bug for negative lat/lon on the GeoTag plugin). However, I've got a map in a page with no GeoTags, and it's appearing in the spatial index on the site, so it has an entry in sitemap.kml.

This means that when the map is loaded, it has a point at the centre for the map page. My intention is only to have GeoTagged pages appear on the map; do you know why this non-tagged page is appearing?

**Comment by edwinwisse** [comment]
I think it is intended that way. If you have a map in your page the center coordinate shows up in tge KML.
You can cheat by also putting a geotag on the page outside the map window. A latitude of 90 should do the trick.

**Comment by iainhallam** [comment]
Interesting; I wonder what the use case is for having your map show up as a data point in itself?

**Comment by mprins** [comment]
maps are indexed by design, the use case is a collection of maps on pages that I have in a namespace and that I want to show in an overview as well as being able to search a map for an area nearby.

- overview: http://wild-water.nl/dokuwiki/beschrijvingen/belgie/start#kaart
- pages eg: http://wild-water.nl/dokuwiki/beschrijvingen/belgie/bocq

I had not noticed this case, but it I don't see how to circumvent this.

**Comment by mprins** [comment]
another use case is using the KML or GeoRSS file in another application
